import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// this is meta tag for the html file.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * @description Renders the root layout of the application.
 * doc for `RootLayout()`
 * @param {Object} props - The props object.
 * @param {React.ReactNode} props.children - The child components to render.
 * @return {JSX.Element} The root layout component.
 */
function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
export default RootLayout;
